language: python

python:
  - 2.7
  - 3.4

env:
  - PROV_TESTS=prov_interop/tests
  - PROV_TESTS=prov_interop/service_tests

install:
  - pip install -r requirements.txt

script: 
  - PROVTRANSLATOR_TEST_CONFIGURATION=config/provtranslator.yaml
  - PROVVALIDATOR_TEST_CONFIGURATION=config/provvalidator.yaml
  - nosetests --nocapture $PROV_TESTS
