language: python

python:
  - 2.7
  - 3.4

install:
  - pip install -r requirements.txt

script: 
 - pwd
 - ls
 - nosetests --version
 - nosetests --nocapture prov_interop.tests
 - nosetests --exe --nocapture prov_interop.tests
