language: python

python:
  - 2.7
  - 3.4

env: 
  matrix:
  - PROV_TESTS=prov_interop/tests
  - PROV_TESTS=prov_interop/service_tests

install:
  - pip install -r requirements.txt

script:
# PROVSTORE_API_KEY value must be defined in Travis CI job configuration
  - echo "API_KEY=$PROVSTORE_API_KEY" >> config.properties
  - mkdir localconfig
  - python prov_interop/customise-config.py config localconfig config.properties
  - nosetests -v --nocapture $PROV_TESTS
