language: python

python:
  - 2.7
  - 3.4

install:
  - pip install -r requirements.txt

script: 
 - pwd
 - ls
 - nosetests --version
 - nosetests --nocapture prov_interop.tests
 - nosetests -v --nocapture prov_interop.tests
 - nosetests -vv --nocapture prov_interop.tests
 - cp -r prov_interop/tests prov_interop/unit_tests
 - nosetests --nocapture prov_interop.unit_tests
