language: python

python:
  - 2.7
  - 3.4

env:
  - PROV_TESTS=prov_interop/tests
  - PROV_TESTS=prov_interop/service_tests/test_provtranslator.py PROVTRANSLATOR_TEST_CONFIGURATION=config/provtranslator.yaml
  - PROV_TESTS=prov_interop/service_tests/test_provvalidator.py PROVVALIDATOR_TEST_CONFIGURATION=config/provvalidator.yaml

install:
  - pip install -r requirements.txt

script: 
  - nosetests --nocapture $PROV_TESTS
