language: python

python:
  - 2.7
  - 3.4

env:
  - PROV_TESTS=prov_interop/tests
  - PROV_TESTS=prov_interop/service_tests

install:
  - pip install -r requirements.txt

script: 
  - cat config.properties
  - mkdir localconfig
  - python prov_interop/customise-config.py config localconfig config.properties
  - nosetests --nocapture $PROV_TESTS
# - nosetests --nocapture prov_interop/tests
