---
test-cases: /home/user/test-cases
comparators:
  ProvPyComparator: 
    class: prov_interop.provpy.comparator.ProvPyComparator
    executable: prov-compare
    arguments: -f FORMAT1 -F FORMAT2 FILE1 FILE2
    # Formats must be in set [json, provn, provx, trig, ttl]
    formats: [provx, json]
