---
ProvStoreConverter:
  class: prov.interop.converter.ProvTranslatorConverter
  url: https://provenance.ecs.soton.ac.uk/store/api/v0/documents/
  api_key: mikej888:XXXXXXXX
  inputs: [provn, ttl, trig, provx, json]
  outputs: [provn, ttl, trig, provx, json]
  skip-tests: [3]
