---
ProvToolboxConverter: 
  class: prov_interop.provtoolbox.converter.ProvToolboxConverter
  executable: PROVTOOLBOX_SCRIPTS_DIR/provconvert
  arguments: [-infile, INPUT, -outfile, OUTPUT]
  # Formats must be in set [json, provn, provx, trig, ttl]
  input-formats: [provn, ttl, trig, provx, json]
  output-formats: [provn, ttl, trig, provx, json]
  skip-tests: [2, 5, 6]
