---
ProvTranslatorConverter:
  class: prov.interop.provtranslator.converter.ProvTranslatorConverter
  url: https://provenance.ecs.soton.ac.uk/validator/provapi/documents/
  input-formats: [provn, ttl, trig, provx, json]
  output-formats: [provn, ttl, trig, provx, json]
  skip-tests: []
