---
ProvPyConverter: 
  class: prov.interop.converter.ProvPyConverter
  directory: /home/user/prov/scripts
  executable: prov-convert
  arguments: [-f, PROV_FORMAT, PROV_INPUT, PROV_OUTPUT]
  inputs: [provn, provx, json]
  outputs: [provn, provx, json]
  skip-tests: [1, 4]
