---
ProvPy: 
  executable: prov-convert
  arguments: -f FORMAT INPUT OUTPUT
  # Formats must be in set [json, provn, provx, trig, ttl]
  input-formats: [json]
  output-formats: [provn, provx, json]
  skip-tests:
    - attr_dict_insert_one_key0
    - attr_dict_insert_one_key1
    - attr_dict_insert_one_key2
    - attr_dict_insert_one_key3
    - attr_dict_insert_one_key4
    - attr_dict_insert_one_key5
    - attr_dict_insert_one_key6
    - attr_dict_insert_one_key7
    - attr_dict_insert_one_key8
    - attr_dict_insert_one_key9
    - attr_dict_insert_one_key10
    - attr_dict_insert_one_key11
    - attr_dict_insert_one_key12
    - attr_dict_insert_one_key13
    - attr_dict_insert_one_key14
    - attr_dict_insert_one_key15
    - attr_dict_insert_one_key16
    - attr_dict_insert_one_key17
    - attr_dict_insert_one_key18
    - attr_dict_insert_one_key19
    - attr_dict_insert_one_key20
    - attr_dict_insert_one_key21
    - attr_dict_insert_one_key22
    - attr_dict_insert_one_key23
    - attr_dict_insert_one_key24
    - attr_dict_insert_one_key25
    - attr_dict_insert_one_key26
    - attr_dict_insert_one_key27
    - attr_dict_insert_one_key28
    - attr_dict_insert_one_key29
    - attr_dict_insert_one_key30
    - attr_dict_insert_one_key31
    - attr_dict_insert_one_key32
    - attr_dict_insert_one_key33
    - attr_dict_insert_one_key34
    - attr_dict_insert_one_key35
    - attr_dict_insert_one_key36
    - attr_dict_insert_one_key37
    - attr_dict_insert_one_key38
    - attr_dict_insert_one_key39
    - attr_dict_insert_one_key40
    - attr_dict_insert_one_key41
    - attr_dict_insert_one_key42
    - dictionaryInsertion1-M
    - dictionaryInsertion1-S
    - dictionaryInsertion2-M
    - dictionaryInsertion2-S
    - dictionaryInsertion3-M
    - dictionaryInsertion3-S
    - dictionaryInsertion4-M
    - dictionaryInsertion4-S
    - dictionaryInsertion5-M
    - dictionaryInsertion5-S
    - dictionaryInsertion6-M
    - dictionaryInsertion6-S
    - dictionaryInsertion7-M
    - dictionaryInsertion7-S
    - dictionaryMembership2-M
    - dictionaryMembership2-S
    - dictionaryMembership3-M
    - dictionaryMembership3-S
    - dictionaryMembership4-M
    - dictionaryMembership4-S
    - dictionaryRemoval1-M
    - dictionaryRemoval1-S
    - dictionaryRemoval2-M
    - dictionaryRemoval2-S
    - dictionaryRemoval3-M
    - dictionaryRemoval3-S
    - dictionaryRemoval4-M
    - dictionaryRemoval4-S
    - dictionaryRemoval5-M
    - dictionaryRemoval5-S

