---
ProvPyConverter: 
  class: prov.interop.provpy.converter.ProvPyConverter
  executable: python
  arguments: [/home/user/prov/scripts/prov-convert, -f, PROV_FORMAT, PROV_INPUT, PROV_OUTPUT]
  inputs: [provn, provx, json]
  outputs: [provn, provx, json]
  skip-tests: [1, 4]
