---
ProvPyConverter: 
  class: prov.interop.provpy.converter.ProvPyConverter
  executable: python
  arguments: [/home/user/prov/scripts/prov-convert, -f, FORMAT, INPUT, OUTPUT]
  input-formats: [provn, provx, json]
  output-formats: [provn, provx, json]
  skip-tests: [1, 4]
