---
test-cases: /home/user/interop/test-cases
converter-tests:
  ProvPy: /home/user/interop/config/provpy.yaml
  ProvToolBox: /home/user/interop/config/provtoolbox.yaml
  ProvTranslator: /home/user/interop/config/provtranslator.yaml
  ProvStore: /home/user/interop/config/provstore.yaml
comparators:
  ProvPyComparator: 
    class: prov.interop.comparator.ProvPyComparator
    executable: python
    arguments: [/home/user/prov/scripts/prov-compare, -f, PROV_FORMAT1, -F, PROV_FORMAT2, PROV_FILE1, PROV_FILE2]
    formats: [provx, json]
  ProvToolboxComparator: 
    class: prov.interop.comparator.ProvToolboxComparator
    executable: /home/user/provToolbox/bin/provcompare
    arguments: [-infile, PROV_INPUT, -outfile, PROV_OUTPUT]
    formats: [provn, ttl, trig, provx, json]
