---
test-cases: /home/user/interop/test-cases
converter-tests:
  ProvPy: /home/user/interop/config/provpy.yaml
  ProvToolBox: /home/user/interop/config/provtoolbox.yaml
  ProvTranslator: /home/user/interop/config/provtranslator.yaml
  ProvStore: /home/user/interop/config/provstore.yaml
comparators:
  ProvPyComparator: 
    class: prov.interop.provpy.comparator.ProvPyComparator
    executable: python
    arguments: [/home/user/prov/scripts/prov-compare, -f, PROV_EXPECTED_FORMAT, -F, PROV_ACTUAL_FORMAT, PROV_EXPECTED_FILE, PROV_ACTUAL_FILE]
    formats: [provx, json]
